### ISSUE TITLE
Unavailable after hass update 2025.2.0

### ISSUE THREAD

**Issue by jansendejong** [cyberjunky/home-assistant-toon_climate#50]
After updating hass to 2025.2.0 Toon entity is unavailable. Everything looks normal and today I've updated hass to 2025.2.1 but still nothing.

**Comment by annedijkstra** [comment]
Same issue here.

**Comment by abelmatser** [comment]
Relevant warning message about configuration:

```
Configuration warnings
Platform error 'sensor' from integration 'toon_smartmeter' - cannot import name 'ENERGY_KILO_WATT_HOUR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
Platform error 'sensor' from integration 'toon_boilerstatus' - Integration 'toon_boilerstatus' not found.
Platform error 'sensor' from integration 'sun2' - cannot import name 'DEVICE_CLASS_TIMESTAMP' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
Platform error 'climate' from integration 'toon_climate' - cannot import name 'CURRENT_HVAC_HEAT' from 'homeassistant.components.climate.const' (/usr/src/homeassistant/homeassistant/components/climate/const.py)
```

**Comment by cyberjunky** [comment]
Update to latest version, I had a user who needed to delete and reinstall, same for toon_smartmeter, all the versions you run are very old.

**Comment by cyberjunky** [comment]
@jansendejong @annedijkstra @abelmatser Did it fix it?

**Comment by abelmatser** [comment]
It did fix it. Thanks for the help @cyberjunky. Like you said, I was indeed on a few years old release 🤷‍♂
